spring:
  application:
    name: zuul-demo

server:
  port: 8040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    test:
      path: /api/*
      url: http://localhost:8030/